# Change the url, username here. Do not change anything else unless you know what you are doing

url=url
username=username
driver=org.postgresql.Driver
classpath=target\\hibernate-liquibase-0.0.1-SNAPSHOT.jar

referenceUrl=hibernate:spring:com.sekwate.backend?dialect=org.hibernate.dialect.PostgreSQLDialect
diffExcludeObjects=.*_view